"""Playwright 自动获取网站 cookies，用于 yt-dlp 下载防护严格的网站（如 Bilibili）"""

import os
import tempfile
import asyncio
from datetime import datetime, timezone
from loguru import logger

# B 站域名列表（按优先级排序）
BILI_DOMAINS = [
    "https://www.bilibili.com",
    "https://bilibili.com",
]

COOKIE_TTL = 600  # cookies 缓存时间（秒），10 分钟内复用


class CookieManager:
    """自动获取并缓存网站 cookies，供 yt-dlp 使用"""

    def __init__(self):
        self._cached_path: str | None = None
        self._cached_time: float = 0

    def _to_netscape_format(self, cookies: list[dict]) -> str:
        """将 Playwright cookies 转换为 Netscape 格式（yt-dlp 兼容）"""
        lines = [
            "# Netscape HTTP Cookie File",
            "# Generated by SubWeaver CookieManager",
            "",
        ]
        for c in cookies:
            domain = c.get("domain", "")
            # 确保 domain 以点开头
            if not domain.startswith("."):
                domain = f".{domain}"
            flag = "TRUE"
            path = c.get("path", "/")
            secure = "TRUE" if c.get("secure") else "FALSE"
            expiry = c.get("expires", 0)
            if expiry == 0 or expiry is None:
                # 没有过期时间的 session cookie 设为一个远期的过期时间
                expiry = int(datetime(2030, 1, 1, tzinfo=timezone.utc).timestamp())
            name = c.get("name", "")
            value = c.get("value", "")
            lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
        return "\n".join(lines)

    async def get_cookies(self, url: str | None = None) -> str | None:
        """
        获取 cookies 文件路径。
        如果缓存有效则复用，否则启动 Playwright 获取。

        Args:
            url: 目标网站 URL，为 None 时尝试预设的 B 站域名列表

        Returns:
            cookies.txt 文件路径，失败返回 None
        """
        now = asyncio.get_event_loop().time()

        # 缓存命中
        if self._cached_path and (now - self._cached_time) < COOKIE_TTL:
            if os.path.isfile(self._cached_path):
                return self._cached_path

        targets = [url] if url else BILI_DOMAINS
        cookies = None

        for target in targets:
            cookies = await self._fetch_cookies(target)
            if cookies:
                break

        if not cookies:
            logger.warning("CookieManager: 所有目标网站均未获取到 cookies")
            return None

        # 写入临时文件
        content = self._to_netscape_format(cookies)
        fd, path = tempfile.mkstemp(suffix=".txt", prefix="cookies_")
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)

        self._cached_path = path
        self._cached_time = now
        logger.info(f"CookieManager: 已获取 {len(cookies)} 个 cookies → {path}")
        return path

    async def _fetch_cookies(self, url: str) -> list[dict] | None:
        """启动 Playwright 访问目标网站，获取 cookies"""
        try:
            from playwright.async_api import async_playwright

            async with async_playwright() as p:
                browser = await p.chromium.launch(
                    headless=True,
                    args=[
                        "--no-sandbox",
                        "--disable-setuid-sandbox",
                        "--disable-dev-shm-usage",
                        "--disable-gpu",
                    ],
                )
                context = await browser.new_context(
                    user_agent=(
                        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                        "AppleWebKit/537.36 (KHTML, like Gecko) "
                        "Chrome/125.0.0.0 Safari/537.36"
                    )
                )
                page = await context.new_page()

                try:
                    await page.goto(url, wait_until="networkidle", timeout=15000)
                    # 等待 cookies 设置完成
                    await page.wait_for_timeout(2000)
                    cookies = await context.cookies()
                    logger.info(f"CookieManager: {url} → 获取到 {len(cookies)} 个 cookies")
                    return cookies
                except Exception as e:
                    logger.warning(f"CookieManager: 访问 {url} 失败: {e}")
                    return None
                finally:
                    await browser.close()
        except Exception as e:
            logger.error(f"CookieManager: Playwright 运行异常: {e}")
            return None

    def cleanup(self):
        """清理缓存的 cookies 文件"""
        if self._cached_path and os.path.isfile(self._cached_path):
            try:
                os.remove(self._cached_path)
            except OSError:
                pass
        self._cached_path = None
        self._cached_time = 0


# 全局单例
cookie_manager = CookieManager()
